# Sonar project properties
sonar.projectKey=dva506-project4
sonar.projectName=DVA506 - Project 4
sonar.projectVersion=1.0

# Sources
sonar.sources=smartmove

# Tests
sonar.tests=tests

sonar.sourceEncoding=UTF-8
sonar.python.version=3

# Coverage report path
sonar.python.coverage.reportPaths=coverage.xml